// The renderer is generated by report.mjs; only its reviewed script may run.
import {TAGS, GLOSSARY} from './tags-en.mjs?v=stage11-review-zh';
import {REVIEW_ZH} from './review-zh.mjs?v=stage11-review-zh';
import {CARD_TEXT, BADGES, TABS, EVIDENCE_NOTE_EN, CITES_HEADER} from './actions-en.mjs?v=stage12-actions-en';
export const rendererHash = 'fQKtISGScDM18HWz01iGnnmkKCK87Vxf41qTner33p0=';
// 看板折叠：每个维度默认只展示前 5 个主标签，其余折叠，可一键展开/收起。
const FOLD_LIMIT = 5;
const foldCss = `
#dimensions .card.voc-fold-collapsed .voc-fold-extra{display:none!important}
.voc-fold-last{position:relative}
.voc-fold-collapsed .voc-fold-last::after{content:'';position:absolute;left:0;right:0;bottom:0;height:12px;background:linear-gradient(180deg,rgba(255,255,255,0),#fff);pointer-events:none}
.voc-fold-btn{display:flex;align-items:center;justify-content:center;gap:7px;width:100%;margin-top:9px;padding:8px 10px;border:1px solid color-mix(in srgb,var(--accent,#4879ce) 28%,#dce5f2);background:color-mix(in srgb,var(--accent,#4879ce) 7%,#f7fafd);color:#3d5a86;border-radius:9px;font-size:12px;font-weight:600;transition:background .15s ease,color .15s ease,border-color .15s ease}
.voc-fold-btn:hover{background:color-mix(in srgb,var(--accent,#4879ce) 15%,#f2f6fc);color:#2b4a77;border-color:color-mix(in srgb,var(--accent,#4879ce) 42%,#dce5f2)}
.voc-fold-btn:focus-visible{outline:2px solid var(--accent,#4879ce);outline-offset:1px}
.voc-fold-chev{width:0;height:0;border-left:4.5px solid transparent;border-right:4.5px solid transparent;border-top:5.5px solid currentColor;transition:transform .18s ease;flex:none}
.voc-fold-btn[aria-expanded="true"] .voc-fold-chev{transform:rotate(180deg)}
`;
// 标签英译层：只作用于评论标签本身，中文以弱化小字跟随；网站框架保持中文。
const tagsEnCss = `
.voc-zh{color:#7c8a9e;font-size:11px;font-weight:400;margin-left:5px}
.tag .voc-zh{font-size:11px}
.pill .voc-zh{font-size:10.5px}
.tag-line{display:flex;justify-content:space-between;align-items:baseline;gap:10px}
.tag-line .count{white-space:nowrap;flex:none;text-align:right}
.journey-card h3 .voc-zh{font-size:12px}
`;
// 评论译文层：评论标题/正文/原声引文原文保留，中文译文以弱化块跟随。
const transCss = `
.voc-trans{display:block;color:#71809a;font-size:11.5px;font-weight:400;line-height:1.65;margin-top:6px;padding-top:6px;border-top:1px dashed #e2e9f3}
td.row-title .voc-trans{margin-top:5px}
blockquote .voc-trans{margin-top:7px}
`;
// 行动建议英译层：标题/论据/行动点附英文对照，并引用支撑该结论的英文买家原声。
const actionsEnCss = `
#actions .voc-en-line{display:block;color:#7c8a9e;font-size:11.5px;font-weight:400;line-height:1.6;margin-top:3px}
#actions h3 .voc-en-line{font-size:12.5px;color:#8a97ab}
#actions .evidence .voc-en-line{font-size:11px;margin-top:2px}
#actions ul .voc-en-line{font-size:11px;margin-top:2px;line-height:1.55}
.voc-tab-en{color:#93a0b4;font-size:11px;font-weight:400;margin-left:6px}
.voc-cites{margin-top:12px;padding-top:9px;border-top:1px dashed #e2e9f3}
.voc-cites-h{font-size:11px;font-weight:600;color:#7c8a9e;margin-bottom:6px;letter-spacing:.02em}
.voc-cite{font-size:12px;color:#51607a;line-height:1.6;margin:5px 0;padding-left:10px;border-left:2.5px solid #dbe4f1}
.voc-cite .voc-star{display:inline-block;font-size:10.5px;color:#b8860b;background:#fdf6e3;border-radius:4px;padding:0 4px;margin-right:6px;vertical-align:1px}
.voc-cite a{color:inherit;text-decoration:none}
.voc-cite a:hover{text-decoration:underline}
.voc-cite-more{font-size:11px;color:#9aa7ba;margin-top:3px}
`;
const foldJs = `
(function(){
 var LIMIT=${FOLD_LIMIT};
 var cards=document.querySelectorAll('#dimensions .card');
 cards.forEach(function(card){
  var groups=[].filter.call(card.children,function(n){return n.classList&&n.classList.contains('tag-group');});
  if(groups.length<=LIMIT)return;
  card.classList.add('voc-fold-collapsed');
  groups.forEach(function(g,i){
   if(i>=LIMIT)g.classList.add('voc-fold-extra');
   if(i===LIMIT-1)g.classList.add('voc-fold-last');
  });
  var btn=document.createElement('button');
  btn.type='button';btn.className='voc-fold-btn';btn.setAttribute('aria-expanded','false');
  var label=document.createElement('span'),chev=document.createElement('span');
  chev.className='voc-fold-chev';chev.setAttribute('aria-hidden','true');
  var sync=function(open){label.textContent=(open?'收起':'展开全部 '+groups.length+' 个标签');};
  sync(false);
  btn.append(label,chev);
  btn.onclick=function(){
   var open=card.classList.toggle('voc-fold-collapsed')===false;
   btn.setAttribute('aria-expanded',String(open));
   sync(open);
  };
  card.appendChild(btn);
 });
})();
`;
const tagsEnJs = `
(function(){
 var TAGS=${JSON.stringify(TAGS)},GLOSS=${JSON.stringify(GLOSSARY)};
 var CJK=/[\\u4e00-\\u9fa5]/;
 var SEL='.tag-line > span:first-child, td .pill';
 var esc=function(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');};
 function fromGlossary(s){
  var total=s.length,out='',covered=0,i,hit;
  while(s.length){
   hit=null;
   for(i=0;i<GLOSS.length;i++){if(s.indexOf(GLOSS[i][0])===0&&(!hit||GLOSS[i][0].length>hit[0].length))hit=GLOSS[i];}
   if(hit){out+=(out?' ':'')+hit[1];covered+=hit[0].length;s=s.slice(hit[0].length);}
   else{covered+=1;s=s.slice(1);}
  }
  return total&&covered/total>=0.75?out:null;
 }
 function en(s){
  if(TAGS[s])return TAGS[s];
  if(s.length<=6)return fromGlossary(s);
  return null;
 }
 function one(el){
  if(!el||el.dataset.vocEn)return;
  var s=(el.textContent||'').trim();
  if(!s||!CJK.test(s))return;
  var e=en(s);
  if(!e)return;
  el.dataset.vocEn='1';
  el.innerHTML=esc(e)+'<span class="voc-zh">'+esc(s)+'</span>';
 }
 var busy=false;
 function pass(root){
  if(busy)return;
  busy=true;
  try{
   var scope=(root&&root.nodeType===1)?root:document.body;
   if(scope.matches&&scope.matches(SEL))one(scope);
   var list=(scope.querySelectorAll?scope.querySelectorAll(SEL):[]);
   for(var i=0;i<list.length;i++)one(list[i]);
  }finally{busy=false;}
 }
 pass(document.body);
 if(window.MutationObserver){
  new MutationObserver(function(muts){
   for(var i=0;i<muts.length;i++){
    var t=muts[i].target;
    pass(t.nodeType===3?t.parentElement:t);
   }
  }).observe(document.body,{subtree:true,childList:true,characterData:true});
 }
})();
`;
const transJs = `
(function(){
 var ZH=${JSON.stringify(REVIEW_ZH)},TAGS=${JSON.stringify(TAGS)};
 var norm=function(s){return String(s).replace(/\\s+/g,' ').trim();};
 var esc=function(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');};
 var LOOKUP={};
 Object.keys(ZH).forEach(function(k){LOOKUP[norm(k)]=ZH[k];});
 function zhOf(s){return LOOKUP[norm(s)]||null;}
 function mark(el){el.dataset.vocTrans='1';}
 // 1) 旅程原声卡片：h3 里“标签名 · N 次”→ 英文+中文；blockquote 追加中文译文
 function voiceCards(){
  document.querySelectorAll('.voice-grid .journey-card').forEach(function(card){
   var h=card.querySelector('h3');
   if(h&&!h.dataset.vocTag){
    var m=h.textContent.trim().match(/^(.*?)(\\s*·\\s*\\d+\\s*次)$/);
    if(m&&TAGS[m[1]]){
     h.dataset.vocTag='1';
     h.innerHTML=esc(TAGS[m[1]])+'<span class="voc-zh">'+esc(m[1])+'</span>'+esc(m[2]);
    }
   }
   var q=card.querySelector('blockquote');
   if(q&&!q.dataset.vocTrans){
    var t=zhOf(q.textContent);
    if(t){mark(q);var s=document.createElement('span');s.className='voc-trans';s.textContent=t;q.appendChild(s);}
   }
  });
 }
 // 2) 评论明细：标题与正文原文保留，下方附中文译文
 function tableRows(){
  document.querySelectorAll('td.row-title, td.body').forEach(function(td){
   if(td.dataset.vocTrans)return;
   var t=zhOf(td.textContent);
   if(!t)return;
   mark(td);
   var s=document.createElement('span');
   s.className='voc-trans';
   s.textContent=t;
   td.appendChild(s);
  });
 }
 var busy=false;
 function pass(){if(busy)return;busy=true;try{voiceCards();tableRows();}finally{busy=false;}}
 pass();
 if(window.MutationObserver){
  new MutationObserver(function(){pass();}).observe(document.body,{subtree:true,childList:true,characterData:true});
 }
})();
`;
const actionsEnJs = `
(function(){
 var TXT=${JSON.stringify(CARD_TEXT)},BADGES=${JSON.stringify(BADGES)},TABS=${JSON.stringify(TABS)};
 var NOTE=${JSON.stringify(EVIDENCE_NOTE_EN)},HEADER=${JSON.stringify(CITES_HEADER)},TAGS=${JSON.stringify(TAGS)};
 var norm=function(s){return String(s).replace(/\\s+/g,' ').trim();};
 var CJK=/[\\u4e00-\\u9fa5]/;
 function enOf(s){return TXT[norm(s)]||null;}
 function line(el,en){if(!el||!en)return;var s=document.createElement('span');s.className='voc-en-line';s.textContent=en;el.appendChild(s);}
 // 数据反查：标签 → 支撑它的英文评论
 var rows=[],MEMBERS={};
 var dataEl=document.getElementById('data');
 if(dataEl){try{
  var d=JSON.parse(dataEl.textContent);
  (d.dimensions||[]).forEach(function(dim){(dim.tags||[]).forEach(function(t){MEMBERS[t.name]=t.members&&t.members.length?t.members:[t.name];});});
  rows=(d.rows||[]).map(function(r){
   var s=[];var L=r.labels||{};
   Object.keys(L).forEach(function(k){if(Array.isArray(L[k]))s=s.concat(L[k]);});
   return {id:r.id,star:r.star,url:r.review_url||'',text:((r.title?r.title+' — ':'')+(r.content||'')).replace(/\\s+/g,' ').trim(),labels:s};
  });
 }catch(e){}}
 function quotesFor(tag){
  var mem=MEMBERS[tag]||[tag],out=[];
  for(var i=0;i<rows.length&&out.length<3;i++){
   var hit=false;
   for(var j=0;j<mem.length;j++){if(rows[i].labels.indexOf(mem[j])>=0){hit=true;break;}}
   if(hit)out.push(rows[i]);
  }
  return out;
 }
 function parseTags(txt){
  var body=txt.replace(/^\\s*[^:]*📊\\s*/,'');
  var k=body.indexOf('（'),note='';
  if(k>=0){note=body.slice(k);body=body.slice(0,k);}
  var parts=[],re=/([^；;]+?)(\\d+)\\s*次/g,m;
  while((m=re.exec(body)))parts.push({name:m[1].trim(),count:m[2]});
  return {parts:parts,note:note};
 }
 // 标签页与区块标题
 document.querySelectorAll('#actions [data-action-tab]').forEach(function(btn){
  var en=TABS[btn.textContent.trim()];
  if(en&&!btn.dataset.vocTab){btn.dataset.vocTab='1';var s=document.createElement('span');s.className='voc-tab-en';s.textContent=en;btn.appendChild(s);}
 });
 var h2=document.querySelector('#actions h2');
 if(h2&&!h2.dataset.vocAct){h2.dataset.vocAct='1';line(h2,enOf(h2.textContent));}
 var note=document.querySelector('#actions .insight-note');
 if(note&&!note.dataset.vocAct){note.dataset.vocAct='1';line(note,enOf(note.textContent));}
 // 卡片
 document.querySelectorAll('#actions article.journey-card').forEach(function(card){
  if(card.dataset.vocAct)return;card.dataset.vocAct='1';
  var badge=card.querySelector('.priority');
  if(badge){var b=BADGES[badge.textContent.trim()];if(b)badge.title=b;}
  line(card.querySelector('h3'),enOf((card.querySelector('h3')||{}).textContent||''));
  var ev=card.querySelector('.evidence');
  if(ev){
   var p=parseTags(ev.textContent);
   if(p.parts.length){
    var enParts=p.parts.map(function(x){return (TAGS[x.name]||x.name)+' ×'+x.count;});
    line(ev,enParts.join('; ')+' '+(p.note.indexOf('重叠')>=0?NOTE.overlap:NOTE.normal));
    // 引用支撑原声
    var seen={},picked=[];
    p.parts.forEach(function(x){quotesFor(x.name).forEach(function(q){if(!seen[q.id]){seen[q.id]=1;picked.push(q);}});});
    if(picked.length){
     var box=document.createElement('div');box.className='voc-cites';
     var hd=document.createElement('div');hd.className='voc-cites-h';hd.textContent=HEADER;box.appendChild(hd);
     picked.slice(0,3).forEach(function(q){
      var el=document.createElement('p');el.className='voc-cite';
      var st=document.createElement('span');st.className='voc-star';st.textContent=q.star+'★';el.appendChild(st);
      var text=q.text.length>170?q.text.slice(0,170).replace(/\\s+\\S*$/,'')+'…':q.text;
      if(q.url){var a=document.createElement('a');a.href=q.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='“'+text+'”';el.appendChild(a);}
      else el.appendChild(document.createTextNode('“'+text+'”'));
      box.appendChild(el);
     });
     if(picked.length>3){var more=document.createElement('div');more.className='voc-cite-more';more.textContent='+'+(picked.length-3)+' more in the review table below';box.appendChild(more);}
     card.appendChild(box);
    }
   }
  }
  card.querySelectorAll('ul li').forEach(function(li){
   if(li.dataset.vocAct)return;li.dataset.vocAct='1';line(li,enOf(li.textContent));
  });
 });
})();
`;
export async function mountReport(frame, html) {
 const doc = new DOMParser().parseFromString(html, 'text/html');
 const scripts = [...doc.querySelectorAll('script')];
 if (scripts.some(s => s.hasAttribute('src')) || doc.querySelector('base, meta[http-equiv="refresh"]')) throw Error('REPORT_SCRIPT');
 const executable = scripts.filter(s => s.type !== 'application/json');
 if (executable.length !== 1) throw Error('REPORT_SCRIPT');
 const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(executable[0].textContent));
 const hash = btoa(String.fromCharCode(...new Uint8Array(bytes)));
 if (![rendererHash, 'ACK+wDQFzOMFU+iHSXMC/KE+Lv04yVfql1PitiY2QMk=', 'u97e7lj3LuYeXUJ9+qIfPF67sg9lEnghZfzDTRSk/U8='].includes(hash)) throw Error('REPORT_SCRIPT');
 // 校验通过后再注入增强，不影响对原始渲染脚本的哈希校验。
 const style = doc.createElement('style');
 style.textContent = foldCss + tagsEnCss + transCss + actionsEnCss;
 doc.head.appendChild(style);
 const fold = doc.createElement('script');
 fold.textContent = foldJs;
 doc.body.appendChild(fold);
 const enhance = doc.createElement('script');
 enhance.textContent = tagsEnJs;
 doc.body.appendChild(enhance);
 const trans = doc.createElement('script');
 trans.textContent = transJs;
 doc.body.appendChild(trans);
 const act = doc.createElement('script');
 act.textContent = actionsEnJs;
 doc.body.appendChild(act);
 frame.srcdoc = '<!DOCTYPE html>' + doc.documentElement.outerHTML;
 frame.hidden = false;
}
