// The renderer is generated by report.mjs; only its reviewed script may run.
import {TAGS, GLOSSARY} from './tags-en.mjs?v=stage10-tags-en';
export const rendererHash = 'fQKtISGScDM18HWz01iGnnmkKCK87Vxf41qTner33p0=';
// 看板折叠：每个维度默认只展示前 5 个主标签，其余折叠，可一键展开/收起。
const FOLD_LIMIT = 5;
const foldCss = `
#dimensions .card.voc-fold-collapsed .voc-fold-extra{display:none!important}
.voc-fold-last{position:relative}
.voc-fold-collapsed .voc-fold-last::after{content:'';position:absolute;left:0;right:0;bottom:0;height:12px;background:linear-gradient(180deg,rgba(255,255,255,0),#fff);pointer-events:none}
.voc-fold-btn{display:flex;align-items:center;justify-content:center;gap:7px;width:100%;margin-top:9px;padding:8px 10px;border:1px solid color-mix(in srgb,var(--accent,#4879ce) 28%,#dce5f2);background:color-mix(in srgb,var(--accent,#4879ce) 7%,#f7fafd);color:#3d5a86;border-radius:9px;font-size:12px;font-weight:600;transition:background .15s ease,color .15s ease,border-color .15s ease}
.voc-fold-btn:hover{background:color-mix(in srgb,var(--accent,#4879ce) 15%,#f2f6fc);color:#2b4a77;border-color:color-mix(in srgb,var(--accent,#4879ce) 42%,#dce5f2)}
.voc-fold-btn:focus-visible{outline:2px solid var(--accent,#4879ce);outline-offset:1px}
.voc-fold-chev{width:0;height:0;border-left:4.5px solid transparent;border-right:4.5px solid transparent;border-top:5.5px solid currentColor;transition:transform .18s ease;flex:none}
.voc-fold-btn[aria-expanded="true"] .voc-fold-chev{transform:rotate(180deg)}
`;
// 标签英译层：只作用于评论标签本身，中文以弱化小字跟随；网站框架保持中文。
const tagsEnCss = `
.voc-zh{color:#7c8a9e;font-size:11px;font-weight:400;margin-left:5px}
.tag .voc-zh{font-size:11px}
.pill .voc-zh{font-size:10.5px}
.tag-line{display:flex;justify-content:space-between;align-items:baseline;gap:10px}
.tag-line .count{white-space:nowrap;flex:none;text-align:right}
`;
const foldJs = `
(function(){
 var LIMIT=${FOLD_LIMIT};
 var cards=document.querySelectorAll('#dimensions .card');
 cards.forEach(function(card){
  var groups=[].filter.call(card.children,function(n){return n.classList&&n.classList.contains('tag-group');});
  if(groups.length<=LIMIT)return;
  card.classList.add('voc-fold-collapsed');
  groups.forEach(function(g,i){
   if(i>=LIMIT)g.classList.add('voc-fold-extra');
   if(i===LIMIT-1)g.classList.add('voc-fold-last');
  });
  var btn=document.createElement('button');
  btn.type='button';btn.className='voc-fold-btn';btn.setAttribute('aria-expanded','false');
  var label=document.createElement('span'),chev=document.createElement('span');
  chev.className='voc-fold-chev';chev.setAttribute('aria-hidden','true');
  var sync=function(open){label.textContent=(open?'收起':'展开全部 '+groups.length+' 个标签');};
  sync(false);
  btn.append(label,chev);
  btn.onclick=function(){
   var open=card.classList.toggle('voc-fold-collapsed')===false;
   btn.setAttribute('aria-expanded',String(open));
   sync(open);
  };
  card.appendChild(btn);
 });
})();
`;
const tagsEnJs = `
(function(){
 var TAGS=${JSON.stringify(TAGS)},GLOSS=${JSON.stringify(GLOSSARY)};
 var CJK=/[\\u4e00-\\u9fa5]/;
 var SEL='.tag-line > span:first-child, td .pill';
 var esc=function(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');};
 function fromGlossary(s){
  var total=s.length,out='',covered=0,i,hit;
  while(s.length){
   hit=null;
   for(i=0;i<GLOSS.length;i++){if(s.indexOf(GLOSS[i][0])===0&&(!hit||GLOSS[i][0].length>hit[0].length))hit=GLOSS[i];}
   if(hit){out+=(out?' ':'')+hit[1];covered+=hit[0].length;s=s.slice(hit[0].length);}
   else{covered+=1;s=s.slice(1);}
  }
  return total&&covered/total>=0.75?out:null;
 }
 function en(s){
  if(TAGS[s])return TAGS[s];
  if(s.length<=6)return fromGlossary(s);
  return null;
 }
 function one(el){
  if(!el||el.dataset.vocEn)return;
  var s=(el.textContent||'').trim();
  if(!s||!CJK.test(s))return;
  var e=en(s);
  if(!e)return;
  el.dataset.vocEn='1';
  el.innerHTML=esc(e)+'<span class="voc-zh">'+esc(s)+'</span>';
 }
 var busy=false;
 function pass(root){
  if(busy)return;
  busy=true;
  try{
   var scope=(root&&root.nodeType===1)?root:document.body;
   if(scope.matches&&scope.matches(SEL))one(scope);
   var list=(scope.querySelectorAll?scope.querySelectorAll(SEL):[]);
   for(var i=0;i<list.length;i++)one(list[i]);
  }finally{busy=false;}
 }
 pass(document.body);
 if(window.MutationObserver){
  new MutationObserver(function(muts){
   for(var i=0;i<muts.length;i++){
    var t=muts[i].target;
    pass(t.nodeType===3?t.parentElement:t);
   }
  }).observe(document.body,{subtree:true,childList:true,characterData:true});
 }
})();
`;
export async function mountReport(frame, html) {
 const doc = new DOMParser().parseFromString(html, 'text/html');
 const scripts = [...doc.querySelectorAll('script')];
 if (scripts.some(s => s.hasAttribute('src')) || doc.querySelector('base, meta[http-equiv="refresh"]')) throw Error('REPORT_SCRIPT');
 const executable = scripts.filter(s => s.type !== 'application/json');
 if (executable.length !== 1) throw Error('REPORT_SCRIPT');
 const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(executable[0].textContent));
 const hash = btoa(String.fromCharCode(...new Uint8Array(bytes)));
 if (![rendererHash, 'ACK+wDQFzOMFU+iHSXMC/KE+Lv04yVfql1PitiY2QMk=', 'u97e7lj3LuYeXUJ9+qIfPF67sg9lEnghZfzDTRSk/U8='].includes(hash)) throw Error('REPORT_SCRIPT');
 // 校验通过后再注入增强，不影响对原始渲染脚本的哈希校验。
 const style = doc.createElement('style');
 style.textContent = foldCss + tagsEnCss;
 doc.head.appendChild(style);
 const fold = doc.createElement('script');
 fold.textContent = foldJs;
 doc.body.appendChild(fold);
 const enhance = doc.createElement('script');
 enhance.textContent = tagsEnJs;
 doc.body.appendChild(enhance);
 frame.srcdoc = '<!DOCTYPE html>' + doc.documentElement.outerHTML;
 frame.hidden = false;
}
